# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectObjects = channel.unary_unary(
                '/doc_ai.vision.Vision/DetectObjects',
                request_serializer=vision__pb2.DetectRequest.SerializeToString,
                response_deserializer=vision__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.OCR = channel.unary_unary(
                '/doc_ai.vision.Vision/OCR',
                request_serializer=vision__pb2.OCRRequest.SerializeToString,
                response_deserializer=vision__pb2.OCRResponse.FromString,
                _registered_method=True)
        self.RecognizeFaces = channel.unary_unary(
                '/doc_ai.vision.Vision/RecognizeFaces',
                request_serializer=vision__pb2.FaceRequest.SerializeToString,
                response_deserializer=vision__pb2.FaceResponse.FromString,
                _registered_method=True)
        self.ProcessVideo = channel.unary_unary(
                '/doc_ai.vision.Vision/ProcessVideo',
                request_serializer=vision__pb2.VideoRequest.SerializeToString,
                response_deserializer=vision__pb2.VideoResponse.FromString,
                _registered_method=True)
        self.QueryScenes = channel.unary_unary(
                '/doc_ai.vision.Vision/QueryScenes',
                request_serializer=vision__pb2.QueryRequest.SerializeToString,
                response_deserializer=vision__pb2.QueryResponse.FromString,
                _registered_method=True)


class VisionServicer:
    """Missing associated documentation comment in .proto file."""

    def DetectObjects(self, request, context):
        """Detect objects in an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OCR(self, request, context):
        """Extract text from an image (OCR)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFaces(self, request, context):
        """Recognize faces in an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessVideo(self, request, context):
        """Process a video file – frame‑by‑frame analysis and scene segmentation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryScenes(self, request, context):
        """Retrieve scenes by semantic query from the vector index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=vision__pb2.DetectRequest.FromString,
                    response_serializer=vision__pb2.DetectResponse.SerializeToString,
            ),
            'OCR': grpc.unary_unary_rpc_method_handler(
                    servicer.OCR,
                    request_deserializer=vision__pb2.OCRRequest.FromString,
                    response_serializer=vision__pb2.OCRResponse.SerializeToString,
            ),
            'RecognizeFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFaces,
                    request_deserializer=vision__pb2.FaceRequest.FromString,
                    response_serializer=vision__pb2.FaceResponse.SerializeToString,
            ),
            'ProcessVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=vision__pb2.VideoRequest.FromString,
                    response_serializer=vision__pb2.VideoResponse.SerializeToString,
            ),
            'QueryScenes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryScenes,
                    request_deserializer=vision__pb2.QueryRequest.FromString,
                    response_serializer=vision__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doc_ai.vision.Vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doc_ai.vision.Vision', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vision:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.vision.Vision/DetectObjects',
            vision__pb2.DetectRequest.SerializeToString,
            vision__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.vision.Vision/OCR',
            vision__pb2.OCRRequest.SerializeToString,
            vision__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.vision.Vision/RecognizeFaces',
            vision__pb2.FaceRequest.SerializeToString,
            vision__pb2.FaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.vision.Vision/ProcessVideo',
            vision__pb2.VideoRequest.SerializeToString,
            vision__pb2.VideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryScenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.vision.Vision/QueryScenes',
            vision__pb2.QueryRequest.SerializeToString,
            vision__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
