# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/doc_ai.inference.Inference/Infer',
                request_serializer=inference__pb2.InferRequest.SerializeToString,
                response_deserializer=inference__pb2.InferResponse.FromString,
                _registered_method=True)
        self.StreamInfer = channel.unary_stream(
                '/doc_ai.inference.Inference/StreamInfer',
                request_serializer=inference__pb2.InferRequest.SerializeToString,
                response_deserializer=inference__pb2.InferResponse.FromString,
                _registered_method=True)


class InferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Unary inference – sends a prompt and returns the full generated text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Streaming inference – sends tokens one by one as they are generated.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__pb2.InferRequest.FromString,
                    response_serializer=inference__pb2.InferResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=inference__pb2.InferRequest.FromString,
                    response_serializer=inference__pb2.InferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doc_ai.inference.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doc_ai.inference.Inference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doc_ai.inference.Inference/Infer',
            inference__pb2.InferRequest.SerializeToString,
            inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/doc_ai.inference.Inference/StreamInfer',
            inference__pb2.InferRequest.SerializeToString,
            inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
