# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x10\x64oc_ai.inference\"[\n\x0cInferRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmodel_name\x18\x04 \x01(\t\"E\n\rInferResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\x32\xa7\x01\n\tInference\x12H\n\x05Infer\x12\x1e.doc_ai.inference.InferRequest\x1a\x1f.doc_ai.inference.InferResponse\x12P\n\x0bStreamInfer\x12\x1e.doc_ai.inference.InferRequest\x1a\x1f.doc_ai.inference.InferResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=37
  _globals['_INFERREQUEST']._serialized_end=128
  _globals['_INFERRESPONSE']._serialized_start=130
  _globals['_INFERRESPONSE']._serialized_end=199
  _globals['_INFERENCE']._serialized_start=202
  _globals['_INFERENCE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
